services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  postgres:
    image: postgres:latest
    environment: &pg-env
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    environment: &django-env
      <<: *pg-env
      DJANGO_DATABASE_HOST: "postgres"
      DJANGO_DATABASE_USER: ${POSTGRES_USER:-postgres}
      DJANGO_DATABASE_NAME: ${POSTGRES_DB:-postgres}
      DJANGO_DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY:-django-insecure-your-secret-key-here}"
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  api-migration:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    command: python manage.py migrate --noinput
    environment:
      <<: *django-env
    depends_on:
      - postgres

  realtime:
    build:
      context: ./backend/realtime
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  ai:
    build:
      context: ./backend/ai_vr
      dockerfile: Dockerfile.ai
    ports:
      - "5000:5000"

  vr:
    build:
      context: ./backend/ai_vr
      dockerfile: Dockerfile.vr
    ports:
      - "5001:5001"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
